
spark.driver.memory 8g
spark.executor.memory 20g
spark.executor.cores 7
spark.executor.instances 2


spark.ui.port 4040


spark.sql.extensions org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
spark.sql.catalog.spark_catalog org.apache.iceberg.spark.SparkSessionCatalog
spark.sql.catalog.spark_catalog.type hive
spark.sql.catalog.local org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.local.type hadoop
spark.sql.catalog.local.warehouse /warehouse
spark.sql.defaultCatalog local


spark.hadoop.fs.s3a.endpoint http://minio:9000
spark.hadoop.fs.s3a.access.key minioadmin
spark.hadoop.fs.s3a.secret.key minioadmin
spark.hadoop.fs.s3a.path.style.access true
spark.hadoop.fs.s3a.impl org.apache.hadoop.fs.s3a.S3AFileSystem
spark.hadoop.fs.s3a.connection.ssl.enabled false


spark.sql.adaptive.enabled true
spark.sql.adaptive.coalescePartitions.enabled true
spark.sql.adaptive.coalescePartitions.minPartitionNum 1
spark.sql.adaptive.advisoryPartitionSizeInBytes 134217728
spark.sql.adaptive.autoBroadcastJoinThreshold 104857600
spark.sql.files.maxPartitionBytes 134217728
spark.sql.shuffle.partitions 400
spark.default.parallelism 400


spark.sql.catalog.local.write.target-file-size-bytes 536870912
spark.sql.catalog.local.write.distribution-mode hash
spark.sql.catalog.local.optimize-data.commit-threshold 10


spark.memory.fraction 0.8
spark.memory.storageFraction 0.3


spark.serializer org.apache.spark.serializer.KryoSerializer 
